### ISSUE TITLE
`.dockerenv` path for checking docker appears to be wrong.

### ISSUE THREAD

**Issue by tomprince** [powersj/whatsthis#18]
The [documentation](https://powersj.github.io/whatsthis/probes/containers/) indicates that this checks `/run/.dockerenv` to detect running in a docker container. However both [the code](https://github.com/moby/moby/blob/6014c1e29dc34dffa77fb5749cc3281c1b4854ac/daemon/initlayer/setup_unix.go#L30) and trying it out suggests that `/.dockerenv` is the file that should be checked.

**Comment by powersj** [comment]
Thanks for filing the issue! Fixed in commit https://github.com/powersj/whatsthis/commit/9031839732350422d543f63930a7b2b3ff7e0f5a
